cmake_minimum_required(VERSION 3.15)
project(ValidateViT LANGUAGES CXX)

add_executable(validate_vit validate_vit.cpp)
target_compile_features(validate_vit PRIVATE cxx_std_17)

add_executable(validate_vit_intermediate validate_vit_intermediate.cpp)
target_compile_features(validate_vit_intermediate PRIVATE cxx_std_17)
